name: Benchmarks
on: [push, pull_request]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [^14, ^16, ^18]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install && yarn global add ts-node
      - run: yarn benchmark
